Added device API support
punica/punica.js pull request #7
Opened 2019-01-21 17:06 UTC by mrNedas

Closes #3

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +  /**
Šiuo metu yra toks niuansas, kad /endpoints ir /devices naudoja skirtingus ID, todėl šita funkciją turėtų neveikti. Geriau dabar išimti.

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +   * @returns {Promise} Promise with a list of endpoints
* Promise duplikojasi
* Ne endpoints, o device registracijos

Siūlyčiau kažką tokio: `@returns {Promise} which fulfills with a list of registered devices`

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +  getDevicesEntries() {
Kad nesimaišytų sų /endpoints device informacija, siūliau pervadinti į `getRegisteredDevices`, o `getDevices` aprašyme įdėti žodelį connected.

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +   * Sends request to get device's PSK ID.
get device registration info/entry

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +   * @param {string} name - Device name
Pakeitėm kad UUID, o ne name.

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +  getDeviceEntry(name) {
getRegisteredDevice?

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +  registerDeviceEntry(entry) {
Siūlau pervadinti į createRegisteredDevice.

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +   * Sends request to register devices.
... to register a new device.

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +   *   // resp = '' (Successfully registered)
Serveris turėtų grąžinti visą info, t.y. psk, psk_id, sugeneruotą uuid.

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +  updateDeviceEntry(name, entry) {
Siūlau pervadint updateRegistaredDevice. Taip pat ne name, o uuid.

2019-02-14 10:32 UTC, GiedriusM commented on punica.js
> +  removeDeviceEntry(name) {
Siūlau pervadinti į `removeRegisteredDevice`.

2019-02-14 14:21 UTC, taubel requested changes

2019-02-14 14:21 UTC, taubel commented on README.md
> +**Returns**: <code>Promise</code> - Promise with device's PSK ID
Doesn't return only device's PSK ID. Should be renamed to device entry.

2019-02-14 14:21 UTC, taubel commented on README.md
> +**Returns**: <code>Promise</code> - Promise with a list of endpoints
I think `Promise with a list of device entries` would be more uniform throughout the readme

2019-02-14 14:21 UTC, taubel commented on README.md
> +  // resp = [{"psk_id": "cHNraWQx", "uuid": "ABC"}, ...]
Device UUID is now generated by the server, so all examples of UUID's in requests, responses etc. should follow the pattern `123e4567-e89b-12d3-a456-426655440000` or simmilar

2019-02-14 14:21 UTC, taubel commented on README.md
> +service.getRegisteredDevicePskId(name).then((resp) => {
I would suggest `getRegisteredDeviceEntry`

2019-02-14 14:21 UTC, taubel commented on tests/punica.test.js
> +      it('should fulfill promise if registration is successfull (201)', () => {
There have been some changes to the API lately. Most importantly, UUID is generated by the server and is returned in the response of the POST request. The current punica API documentation does not reflect this, and will be fixed soon. You later can use the returned UUID during tests where you edit/delete/get a specific device entry.

2019-02-18 08:45 UTC, GiedriusM requested changes

2019-02-18 08:45 UTC, GiedriusM commented on punica.js
> +  updateRegistaredDevice(uuid, entry) {
Typo: should be Registered instead of Registared.

2019-02-25 11:10 UTC, GiedriusM approved these changes

2019-02-25 11:12 UTC, merged